services:
  nginx:
    image: nginx:latest
    ports: [80:80, 443:443]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
  identity-service:
    build: ./identity
    ports: [5000:5000]
    volumes:
      - ./identity/config.yml:/app/config.yml:ro
      - ./keys:/app/keys:ro
    depends_on:
      - redis
  file-storage-service:
    build: ./file-storage
    ports: [5004:5004]
    volumes:
      - ./file-storage/config.yml:/app/config.yml:ro
      - ./keys/rsa.pub:/app/keys/rsa.pub:ro
    environment:
      FILE_STORAGE_AWS_ACCESS_KEY_ID: ${FILE_STORAGE_AWS_ACCESS_KEY_ID}
      FILE_STORAGE_AWS_REGION: ${FILE_STORAGE_AWS_REGION}
      FILE_STORAGE_AWS_ENDPOINT_URL: ${FILE_STORAGE_AWS_ENDPOINT_URL}
      FILE_STORAGE_AWS_SECRET_ACCESS_KEY: ${FILE_STORAGE_AWS_SECRET_ACCESS_KEY}
      FILE_STORAGE_DB_DSN: host=postgres port=5432 user=postgres password=secret dbname=file_metadata sslmode=disable
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:latest
    ports: [5432:5432]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=file_metadata
  redis:
    image: redis:latest
    ports: [6379:6379]
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=secret
volumes:
  redis_data:
  postgres_data: