services:
  nginx:
    image: nginx:latest
    ports: [80:80]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  identity_service:
    build: ./identity
    ports: [5000:5000]
    volumes:
      - ./identity/config.yml:/app/config.yml
      - ./identity/keys:/app/keys
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports: [6379:6379]
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=secret
volumes:
  redis_data: