jwt:
  signing_method: RS256
  issuer: identity_service
  audience:
    - messaging_service
  key_file_path: /app/keys/rsa.pub

redis:
  addr: messaging-redis:6379
  db: 0

file_storage:
  grpc_addr: file-storage-service:9090

otlp:
  grpc_addr: otel-collector:4317