jwt:
  signing_method: RS256
  issuer: identity_service
  audience:
    - messaging_service
  key_file_path: /app/keys/rsa.pub

redis:
  addr: messaging-redis:6379
  password: secret
  db: 0

otlp:
  grpc_addr: otel-collector:4317