access_token:
  signing_method: HS512
  lifetime: 5m # Just for demo
  issuer: identity_service
  audience: 
    - client
  key_file_path: /app/keys/sym
refresh_token:
  signing_method: HS512
  lifetime: 30m # Just for demo
  issuer: identity_service
  audience: 
    - client
  key_file_path: /app/keys/sym
internal_token:
  signing_method: RS256
  lifetime: 1m # Just for demo
  issuer: identity_service
  audience: 
    - identity_service
  key_file_path: /app/keys/rsa
invalidated_token_storage:
  exp: 4m # A little bit longer than refresh_token.lifetime
userservice:
  grpc_addr: user-service:5051
redis:
  addr: identity-redis:6379
  password: secret
  db: 0
signin_meta:
  lifetime: 2m
signup_meta:
  lifetime: 2m
idempotency:
  data_exp: 10m
phone_code:
  send_frequency: 1m
sms:
  type: stub
  stub:
    addr: http://sms-service-stub:5023
otlp:
  grpc_addr: otel-collector:4317