jwt:
  signing_method: RS256
  lifetime: 3m
  issuer: identity_service
  audience: 
    - file_storage_service
  key_file_path: /app/keys/rsa.pub
redis:
  addr: file-storage-redis:6379
  password: secret
  db: 0
idempotency:
  data_exp: 10m
upload:
  file_size_limit: 10485760 # 10MB
multipart_upload:
  min_file_size: 524288000 # 10MB
  max_part_size: 1048576 # 100MB
otlp:
  grpc_addr: otel-collector:4317
grpc_service:
  port: 9090