{{- $secretId := .Values.secretId -}}
{{- range $key, $value := .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: {{ $key }}
    template:
      type: {{ $value.type | default "kubernetes.io/Opaque" }}
      engineVersion: v2
      {{- with $value.data }}
      data:
        {{- range $datakey, $datavalue := . }}
        {{ $datakey }}: {{- if typeIs "string" $datavalue }} {{$datavalue | quote}} {{- else }} {{"|"}}
        {{- $datavalue | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- end }}
  dataFrom:
    - extract:
        key: {{ $secretId }}
---
{{- end }}
