jwt:
  signing_method: RS256
  lifetime: 3m
  issuer: identity_service
  audience: 
    - user_service
  key_file_path: /app/keys/rsa.pub

kafka:
  brokers: ml-kafka:9092
  consume_topic:  updates
  produce_topic: notifq
# Ann, you look here and think what is happening here
# Here should be two separate Kafka configs to two separate kafka "clusters" 
