name: Identity Service Unit Test

on:
  push:
    branches:
      - '**'
    paths:
        - backend/identity/**.go
        - backend/identity/**/go.mod
        - .github/workflows/identity-service-unit-test.yaml
  pull_request:
    branches:
      - main
    paths:
      - backend/identity/**.go
      - backend/identity/**/go.mod
      - .github/workflows/identity-service-unit-test.yaml
jobs:
    unit-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.23.1
        - name: Test
          run: |
            cd backend/identity
            go test -v -race ./..