name: Run Identity Service Tests in Docker 

on:
  push:
    branches:
      - '**'
    paths:
      - identity-service/**
      - .github/workflows/identity-service-test.yaml
      - tests/identity-service/**
  pull_request:
    branches:
      - main
    paths:
      - identity-service/**
      - .github/workflows/identity-service-test.yaml
      - tests/identity-service/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Compose
        id: docker-compose-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/docker-compose
          key: ${{ runner.os }}-docker-compose-v2 # Use Docker Compose version in the key
          restore-keys: |
            ${{ runner.os }}-docker-compose-

      - name: Install Docker Compose if not cached
        run: |
          if [ ! -f /usr/local/bin/docker-compose ]; then
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

      - name: Verify Docker Compose is available
        run: docker-compose --version

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-layers-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-layers-

      - name: Generate keys
        run: | 
          cd tests/identity-service
          make keys-rsa
          make keys-sym
          cd ../..

      - name: Build
        run: |
          docker-compose -f tests/identity-service/docker-compose.yml \
          build --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Run tests
        run: |
          docker-compose -f tests/identity-service/docker-compose.yml \
          up --abort-on-container-exit --exit-code-from test

      - name: Tear down
        if: always()
        run: docker-compose -f tests/identity-service/docker-compose.yml down
