name: Messaging Service Unit Test

on:
  push:
    branches:
      - '**'
    paths:
        - messaging-service/**.go
        - messaging-service/**/go.mod
        - .github/workflows/messaging-service-unit-test.yaml
  pull_request:
    branches:
      - main
    paths:
      - messaging-service/**.go
      - messaging-service/**/go.mod
      - .github/workflows/messaging-service-unit-test.yaml
jobs:
    unit-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.23.1
        - name: Test
          run: |
            cd messaging-service
            go test -v -race ./...