name: Shared Go Library Unit Test

on:
  push:
    branches:
      - '**'
    paths:
        - backend/shared/go/**.go
        - backend/shared/go/**/go.mod
        - .github/workflows/shared-lib-unit-test.yaml
  pull_request:
    branches:
      - main
    paths:
      - backend/shared/go/**.go
      - backend/shared/go/**/go.mod
      - .github/workflows/shared-lib-unit-test.yaml
jobs:
    unit-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.23.1
        - name: Test
          run: |
            cd backend/shared/go
            go test -v -race ./...